# Config pour les tests en local avec l'extension Databricks
catalog_name: workspace
schema_name: prod
experiment_name: /Shared/info98_mlops_2025

dev:
  catalog_name: workspace
  schema_name: dev
  experiment_name: /Shared/info98_mlops_2025

prod:
  catalog_name: workspace
  schema_name: prod
  experiment_name: /Shared/info98_mlops_2025

parameters:
  learning_rate: 0.01
  n_estimators: 100
  max_depth: 6

num_features:
  - fixed_acidity
  - volatile_acidity
  - citric_acid
  - residual_sugar
  - chlorides
  - free_sulfur_dioxide
  - total_sulfur_dioxide
  - density
  - pH
  - sulphates
  - alcohol

cat_features:
  - type

target: quality
